In [1]:
import numpy as np


In [3]:
## Step Zero
##Read inputs and outputs

#X =np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
X =np.array([[1,0,1,0],[1,0,1,1]])
Y = np.array([[1,0]]).T

In [4]:
##Step 1
## Initialize weights and biases with random values 
#(There are methods to initialize weights and biases but 
#for now initialize with random values)
np.random.seed(42) ##seeding 

##weights and bias for Hidden layer
W_HL = 2 * np.random.random((4,3)) -1 ## sacling between -1 to +1
B_HL = 2 * np.random.random((1,3)) - 1


## weights and bias for output layer
W_OL =  2 * np.random.random((3,1)) - 1
B_OL = 2 * np.random.random((1,1)) - 1


In [5]:
B_HL

array([[ 0.66488528, -0.57532178, -0.63635007]])

In [7]:
##Step2 calculate hidden layer input
#hidden_layer_input = matrix_dot_product(X,wh) + bh
HL_input =  np.dot(X,W_HL) + B_HL

(4, 3)

In [8]:
HL_input

array([[-0.46986726,  1.05845913,  0.02986784],
       [-0.0537221 ,  0.09962811,  0.96968755]])

In [9]:
##Step 3: Perform non-linear transformation on hidden linear input
#hidden layer activations

def sig(x):
    return 1/(1+ np.exp(-x))


HL_activations = sig(HL_input)
    

In [10]:
HL_activations

array([[0.38464766, 0.74239597, 0.50746641],
       [0.4865727 , 0.52488645, 0.72505721]])

In [11]:
##Step 4: Perform linear and non-linear transformation of hidden layer activation
## at outputlayer
OL_input = np.dot(HL_activations,W_OL) + B_OL

In [12]:
## Step 5 output at outputlayer
output = sig(OL_input)

In [13]:
## BACK PROPAGATION STARTS
#Step 5: Calculate gradient of Error(E) at output layer
Err = Y-output

In [14]:
Err


array([[ 0.65592771],
       [-0.35119173]])

In [15]:
#Step 6: Compute slope at output and hidden layer

def deri_sig(x):
    return x*(1-x)



In [16]:
#Slope_output_layer= derivatives_sigmoid(output)
derivative_OL = deri_sig(output)

#Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
derivative_HL = deri_sig(HL_activations)

In [17]:
##Step 7: Compute delta at output layer
O_delta = Err*derivative_OL



In [19]:
##Step 8: Calculate Error at hidden layer

Err_HL = np.dot(O_delta, W_OL.T)

In [20]:
##Step 9: Compute delta at hidden layer

H_delta = Err_HL * derivative_HL

In [21]:
##Step 10: Update weight at both output and hidden layer
learning_rate =1
W_OL = W_OL + np.dot(HL_activations.T, O_delta) * learning_rate
W_HL = W_HL + np.dot(X.T,H_delta) * learning_rate

In [46]:
##Step 11: Update bias of both Output and Hidden Layer
B_HL = B_HL + np.sum(H_delta,axis=0)*learning_rate
B_OL = B_OL + np.sum(O_delta,axis=0)* learning_rate